### ISSUE TITLE
Asking for the code of the model

### ISSUE THREAD

**Issue by Lamsoda** [FanzhenLiu/DAGAD#3]
Can't find your related code (Model and Loss func). May you kindly upload it again? Reallly need it since I can not recurrence your experiment, not even the baseline. I still dont know which part that I mess up. Looking for your help!!

**Comment by Lamsoda** [comment]
no need, seen it in history.

**Comment by FanzhenLiu** [comment]
Sorry for the late reply and bringing you inconvenience. I just got back from other things. 

We are happy to hear that our paper on ICDM was able to inspire you. The deleted file DAGAD.py is the draft version with bugs, so we deleted it. Currently, we are preparing a long version of this work for submission to a journal, and the code will be available once our long version is accepted.
